/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ledgerco;


import com.ledgerco.io.input.commands.CommandFactory;
import com.ledgerco.io.input.FileInputParser;
import com.ledgerco.io.input.commands.ICommand;
import org.junit.jupiter.api.Test;
import org.mockito.InOrder;

import java.util.ArrayList;
import java.util.Arrays;

import static org.mockito.Mockito.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() throws Exception {
        FileInputParser inputParser = mock(FileInputParser.class);
        LedgerApp ledgerApp = mock(LedgerApp.class);
        CommandFactory commandFactory = mock(CommandFactory.class);

        String filePath = "file-path";
        ArrayList<String> inputLines = new ArrayList<>();
        when(inputParser.parse(filePath)).thenReturn(inputLines);
        ICommand command1 = mock(ICommand.class);
        ICommand command2 = mock(ICommand.class);
        ICommand command3 = mock(ICommand.class);
        when(commandFactory.create(inputLines))
                .thenReturn(Arrays.asList(command1, command2, command3));

        new App(inputParser, commandFactory, ledgerApp).run(filePath);

        InOrder inOrder = inOrder(inputParser, command1, command2, command3);
        inOrder.verify(inputParser).parse(filePath);
        inOrder.verify(command1).execute(ledgerApp);
        inOrder.verify(command2).execute(ledgerApp);
        inOrder.verify(command3).execute(ledgerApp);
    }
}
